---
registry:
  host: "registry.hub.docker.com"

clair:
  host: "192.168.99.100:30983"

output:
  format: short-table # "json", "table", "short-table" or quiet
# uncomment if you want to use the rocketchat output feature
#  rocketchat:
#    webhook_url: rocket-chat.com/hooks/...
#    receiver: "#general,@admin"

fail_on:
  # a number will be added to the score depending on the severity
  # unknown: 0, negligible: 1, low: 16, medium: 81, high: 265, critical: 625, defcon1: 1296 
  score: 2018
  big_vulnerability: true
